version: '3.8'

services:
  web:
    build: .
    container_name: dogovorai_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # Заставляем бэкэнд смотреть на локальный контейнер с Postgres
      - DATABASE_URL=postgresql+asyncpg://dionysus_user:panopticon_pass@db:5432/startup_db
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: dogovorai_postgres
    environment:
      - POSTGRES_USER=dionysus_user
      - POSTGRES_PASSWORD=panopticon_pass
      - POSTGRES_DB=startup_db
    # Закрываем порты от внешнего мира ради тотальной безопасности
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dionysus_user -d startup_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge