version: '3.8'

services:
  web:
    build: .
    container_name: dogovorai_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # Заставляем бэкэнд смотреть на локальный контейнер с Postgres
      - DATABASE_URL=postgresql://dionysus_user:panopticon_pass@db:5432/startup_db
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: dogovorai_postgres
    environment:
      - POSTGRES_USER=dionysus_user
      - POSTGRES_PASSWORD=panopticon_pass
      - POSTGRES_DB=startup_db
    # Закрываем порты от внешнего мира ради тотальной безопасности
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dionysus_user -d startup_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: dogovorai_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - web

  grafana:
    image: grafana/grafana:latest
    container_name: dogovorai_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge