# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
timezone = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file as a
# standalone script, false to use exec() mode
# run_environment_as_script = false

# This shouldn't be set while using tags or branches.
# version_path_separator = :

# the output encoding used when revision files
# are written from script.py.mktemplate()
# output_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://postgres:postgres@dogovorai_postgres:5432/postgres


[post_write_hooks]
# post_write_hooks defines scripts or Python functions Alembic will run
# after generating a new revision file.

# format using "pep8" or "black" to run autopeppling on new migration scripts.
# defaults to no post write hook
hooks = black

# pep8_args is optional. defaults to ""
pep8_args = --line-length=100

# black_args is optional. defaults to ""
black_args = -l 100


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S